version: "3"
services:

  django:
    image: python:3.6
    volumes:
      - .:/src
      - venv:/src/venv
    command: ["/src/tools/dev-django.sh", "0.0.0.0:8000"]
    environment:
      ADMIN_USERNAME: "${DJANGO_ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${DJANGO_ADMIN_PASSWORD}"
      ADMIN_EMAIL: "${DJANGO_ADMIN_EMAIL}"
      DATABASE_URL: "${DJANGO_DATABASE_URL}"
      ALLOW_SIGNUP: "${DJANGO_ALLOW_SIGNUP}"
      USE_MAILJET: "${DJANGO_USE_MAILJET}"
      MAILJET_API_KEY: "${DJANGO_MAILJET_API_KEY}"
      MAILJET_SECRET_KEY: "${DJANGO_MAILJET_SECRET_KEY}"
      WEBPACK_ENVIRONMENT_PRODUCTION: "${WEBPACK_ENVIRONMENT_PRODUCTION}"
    ports:
      - 8000:8000

  webpack:
    image: node:8
    volumes:
      - .:/src
      - node_modules:/src/src/server/static/node_modules
    command: ["/src/tools/dev-webpack.sh"]
    environment:
      WEBPACK_ENVIRONMENT_PRODUCTION: "${WEBPACK_ENVIRONMENT_PRODUCTION}"
      WEBPACK_HOST: "${WEBPACK_HOST}"
      WEBPACK_PORT: "${WEBPACK_PORT}"
      WEBPACK_POLL_MILLIS: "${WEBPACK_POLL_MILLIS}"
    ports:
      - 8080:8080

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: ${PGDATA}
    ports:
      - 5432:5432
    volumes:
      - ./src/db:/var/lib/postgres/data

volumes:
  node_modules:
  venv:
